//script generated by SiteXpert (www.xtreeme.com/sitexpert/)
//Copyright(C) 1998-2003 Xtreeme GmbH
NS60=(navigator.userAgent.indexOf("Netscape6/6.0")!=-1)
Opera=(navigator.userAgent.indexOf('Opera')!=-1)||(navigator.appName.indexOf('Opera')!=-1)||(window.opera)
Opera7=(Opera&&document.createElement!=null&&document.addEventListener!=null)
IE4=(document.all&&!Opera)
mac=((IE4)&&(navigator.appVersion.indexOf("Mac")!=-1))
DOM=document.documentElement&&!IE4&&!Opera
NS4=navigator.appName.indexOf("Netscape")>-1&&!DOM
mswnd=(navigator.appVersion.indexOf("Windows")!=-1||navigator.appVersion.indexOf("WinNT")!=-1)
if(IE4){
av=navigator.appVersion
avi=av.indexOf("MSIE")
if(avi==-1){version=parseInt(av);}else{version=parseInt(av.substr(avi+4));}}
var ver='6.1.4EnStd'
var m1=new Object
m1.name='m1'
m1.fnm='sitemap_m1'
if(!window.lastm||window.lastm<1)lastm=1
if(NS4||IE4||DOM||Opera){
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.scrollDelay=50
m1.scrollStep=10
m1.showDelayedTimeout=null
m1.fadingSteps=8
m1.v21="."
m1.maxlev=2
m1.v22=0
m1.bVarWidth=0
m1.bShowDel=0
m1.v23=180
m1.levelOffset=20
m1.bord=1
m1.vertSpace=4
m1.sep=1
m1.v19=false
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.v20=false
m1.cntFrame="content"
m1.menuFrame="tree"
m1.v24="content"
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg="#3A6EA5"
m1.tlmOrigCol="#FFFFFF"
m1.v25=false
m1.popupOpacity=0
m1.v11=false
m1.rm=-1
m1.v10=0
m1.popupLeftPad=5
m1.v01=2
m1.tlmHlBg="#92ADC0"
m1.tlmHlCol="#FFFFFF"
m1.borderCol="#FFFFFF"
m1.menuHorizontal=true
m1.scrollHeight=6}
m1.lev0=new Array("11px",false,false,"#FFFFFF","#3A6EA5","#FFFFFF","Arial,Verdana,Tahoma","#92ADC0")
m1.lev1=new Array("11px",false,false,"#FFFFFF","#3A6EA5","#FFFFFF","Arial,Verdana,Tahoma","#92ADC0")
m1.lev2=new Array("11px",false,false,"#FFFFFF","#3A6EA5","#FFFFFF","Arial,Verdana,Tahoma","#92ADC0")
m1mn1=new Array
(
"Book Store","bookorder.php",0
,"Calendars","",1
,"Ceremonies","",1
,"Charities","",1
,"Committees","",1
,"Conferences","",1
,"Information Center","infocntr.php",0
,"Jewlery and Gifts","jewlery.php",0
,"Maps","",1
,"News and Events","#",1
,"Officers","",1
,"Photographs","",1
,"Programs","",1
,"Publications","",1
)
m1mn1_2=new Array
(
"Advanced Planning","advance-planning.php",0
,"Committee on Work","com-work.php",0
,"Events and Activities","events-nov.php",0
,"Grand Master's Schedule","schedule.php",0
)
m1mn1_3=new Array
(
"Corner Stone Ceremonies","cornerstones.php",0
)
m1mn1_4=new Array
(
"<!--_blank-->Grotto Humanitarian Foundation","http://www.scgrotto.com/Text%20documents/HFhome.htm",0
,"<!--_blank-->Knights Templar Eye Foundation","http://ww.knightstemplar.org/ktef/",0
,"Masonic Charities","charity.php",0
,"<!--_blank-->Masonic Home and School","http://mhstx.org/",0
,"<!--_blank-->Order of DeMolay","http://www.demolay.org/giving/",0
,"Sam Houston Hall of Fame","hallfame.php",0
,"<!--_blank-->Scottish Rite Dormitory","http://www.srd.org",0
,"<!--_blank-->Shriners Hospital - Galveston","http://www.shrinershq.org/shc/galveston/index.html",0
,"Shriners Hospital - Houston","http://www.shrinershq.org/shc/houston/index.html",0
,"Texas Masonic Philanthropies","tmp.php",0
,"<!--_blank-->Texas Masonic Retirement Center","http://www.txmrc.org",0
,"<!--_blank-->Texas Scottish Rite Chjildren's Hospital","http://www.tsrhc.org",0
)
m1mn1_5=new Array
(
"Committee Chairmen","committees.php",0
,"Committee on Work","com-work.php",0
,"Committee on Work Schedules","com-work-griffin.php",0
,"Grand Lodge Committees","committees.php",0
,"Internet Committee","glic.php",0
)
m1mn1_6=new Array
(
"Wardens Retreat","wardens.php",0
)
m1mn1_9=new Array
(
"Map of Downtown Waco","map.php",0
,"Texas Masonic Retirement Center","tmrc-map.php",0
,"To Grand Lodge","map.php",0
)
m1mn1_10=new Array
(
"Trestleboard Online","news.php",0
)
m1mn1_11=new Array
(
"Grand Master of Texas Masons","gm-bio.php",0
,"Grand Master's Schedule","schedule.php",0
,"Grand Lodge Officers","officers.php",0
,"Grand Lodge Officer's Schedules","schedule.php",0
,"Past Grand Masters","pastgms.php",0
)
m1mn1_12=new Array
(
"<!--_blank-->Grand Lodge Library - Historical","http://www.library-museum.grandlodgeoftexas.org/",0
,"Tour of the Grand Lodge","tour-1.php",0
)
m1mn1_13=new Array
(
"Archived Educational Programs","masonic-educational-programs.php",0
,"Current Educational Programs","gm-educational-programs.php",0
)
m1mn1_14=new Array
(
"Texas Mason Magazine","txmason.php",0
,"Texas Masonic News","news.php",0
)
m1mn2=new Array
(
"Listed by City","a-lodges.php",0
,"Listed by Lodge Name","lodge_name_a.php",0
)
m1mn3=new Array
(
"Alamo Remembered","alamo.php",0
,"Masonic Oak Celebration","m-may.php",0
,"Goliad Observance","goliad-2001.php",0
,"San Jacinto Memorial","m-apr.php",0
)
m1mn4=new Array
(
"167 Years of Masonry in Texas","167years.php",0
,"David Crockett","crockett.php",0
,"James Bonham","bonham.php",0
,"James Bowie","bowie.php",0
,"James Fannin","fannin.php",0
,"Masonic Oak Observance","mas-oak.php",0
,"R.E.B. Baylor","baylor.php",0
,"Rembering the Alamo","alamo.php",0
,"Sam Houston","sam-hou.php",0
,"San Jacinto Observance","m-apr.php",0
,"Stephen F. Austin","austin.php",0
,"Texas Masoic Heros","heros.php",0
,"The Grand Lodge of the Republic of Texas","m-dec.php",0
,"William B. Travis","travis.php",0
)
m1mn5=new Array
(
"<!--_blank-->DeMolay International","http://demolay.org/home/index.shtml",0
,"Jobs Daughters","jobsdau.php",0
,"<!--_blank-->Masonic Home and School","http://www.mhstx.org/",0
,"<!--_blank-->Order of the Eastern Star","http://www.grandchapteroftexas.org/",0
,"<!--_blank-->Scottish Rite Dormitory","http://www.srd.org/",0
,"Scottish Rite/YorkRite/Others","links.php",0
,"Shrine","shrine.php",0
,"Shriners Hospital - Galveston","http://www.shrinershq.org/shc/galveston/index.html",0
,"<!--_blank-->Shriners Hospital - Houston","http://www.shrinershq.org/shc/houston/index.html",0
,"<!--_blank-->Texas DeMolay Online","http://texasdemolay.org/",0
,"<!--_blank-->Texas Lodge of Research","http://pentium2.gower.net/Community/tir/",0
,"Texas Masonic Retirement Center","http://www.txmrc.org",0
,"<!--_blank-->Texas Rainbow Grand Assembly","http://serve.com/texas/",0
,"<!--_blank-->Texas Scottish Rite Children's Hospital","http://www.tsrhc.org/",0
,"<!--_blank-->Tranquility Lodge 2000","http://www.tranquilitylodge2000.org/",0
,"<!--_blank-->York Rite","http://www.texasyorkrite.org/",0
)
m1mn6=new Array
(
"Information Page","lodgesecretary.php",0
)
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("/")) {sepCh = "\\" ;} else {sepCh = "/" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.popupOffset=0
m1.v02=m1.v23
if(Opera&&!Opera7)document.write("<"+"script language='JavaScript1.2' src='./menu_opera.js'><"+"/"+"script>")
else if(NS4)document.write("<"+"script language='JavaScript1.2' src='./menu_ns4.js'><"+"/"+"script>")
else if(document.getElementById)document.write("<"+"script language='JavaScript1.2' src='./menu_dom.js'><"+"/"+"script>")
else document.write("<"+"script language='JavaScript1.2' src='./menu_ie4.js'><"+"/"+"script>")
document.write("<style type='text/css'>\n")
document.write(".m1CL0{text-decoration:none;color:#FFFFFF; }\n")
document.write(".topFold{position:"+(!DOM&&!IE4?"relative":"static")+"}\n")
if(NS4&&!m1.v25)document.write(".x1{padding-left:10px;padding-right:10px;}\n")
document.write(".m1mit{"+((!NS4||m1.v25)?"padding-left:10px;padding-right:10px;":"")+"color:#FFFFFF; font-family:Arial,Verdana,Tahoma; font-size:11px; }\n")
document.write("</style>\n\n")
